# Generated by Django 3.0.6 on 2021-08-15 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('ano', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('balance', models.IntegerField()),
                ('atype', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('mobile', models.IntegerField()),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('pincode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('tno', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('fromano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_from_account', to='mybank.Account')),
                ('toano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_to_account', to='mybank.Account')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='cid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mybank.Customer'),
        ),
    ]
