# Generated by Django 3.0.6 on 2021-08-16 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='tno',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
